### ISSUE TITLE
NOTE_001 Overview

### ISSUE THREAD

**Issue by sw20-tugraz** [sw20-tug/ASD-Morning-9#1]
As a user I want to see all my notes on the screen directly after opening the app to get an overview.

**Acceptance criteria:**
- All notes are displayed on the start screen
- Scales depending on the screen-size

**Comment by weniseb** [comment]
- [x] List Note with title and a short content preview
- [ ] Add a edit button to every note
- [ ] Add a remove button to every Note
- [ ] Make visible which note correspond to wich tag
